using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

//generated by VS.

namespace Task52_53
{
    internal class ReadOnlyFile
    {
    }
}
